### ISSUE TITLE
Client-side script inclusion with <script src..> should be made modular in all html files

### ISSUE THREAD

**Issue by app4mc-rover** [app4mc-rover/rover-web#1]
Unfortunately, entering http://127.0.0.1:5052/socket.io/socket.io.js or http://localhost:5052/socket.io/socket.io.js does not work. 

Entering http;//192.168.168.1:5052/socket.io/socket.io.js works, but it is not modular.

Dynamically obtaining host also did not work so far. This needs to be solved.

**Comment by mozcelikors** [comment]
Latest commit fixes this.
